server:
  port: 9400
  servlet:
    context-path: /api/jpacrud/cms
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  jwt:
    secret: secretkey1!
  thymeleaf:
    enabled: false
  datasource:
    url: jdbc:mariadb://localhost:3306/jpacrudcms?serverTimezone=Asia/Seoul
    username: jpacrudcms
    password: jpacrudcms
    datasource: driver-class-name=org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 100
#  spring-doc:
#    api-docs:
#      groups:
#        enabled: true
#    swagger-ui:
#      path: /swagger-ui.index.html
#      displayRequestDuration: true
#      groups-order: DESC
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
app:
# filePath: /Users/사용자명/jpacrud/cms/resource # 맥OS
#filePath: C://경로/CMS/resource # 윈도우즈
filePath: /home/bit/jpacrud/cms/resource
hash: hash1!
billing: billing1!